import { Navbar } from '@/components'
import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <Head>

      <link rel="icon" href="/favicon.ico" />
      </Head> */}
       <div className="w-full flex flex-col items-center">
          <div className="w-full max-w-[80%] ">
            <Navbar />
            {children}
          </div>
        </div>
    </html>
  )
}
